name: carbon-credits
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit=1.31.0
  - pandas=2.2.0
  - plotly=5.18.0
  - reportlab=4.0.8
  - openpyxl=3.1.2
  - numpy=1.26.3
  - pip
  - pip:
    - numpy-financial==1.0.0 