name: carbon-credits
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - plotly
  - reportlab
  - openpyxl
  - numpy
  - pip
  - pip:
    - numpy-financial 