[theme]
primaryColor = "#4169E1"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
enableStaticServing = false
runOnSave = false
maxUploadSize = 200
enableCORS = false

[browser]
gatherUsageStats = false 